services:
    db:
        image: postgres:15
        container_name: my_project_db
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypass
            POSTGRES_DB: mydb
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        # Optional restart policy
        restart: unless-stopped

    web:
        build: .
        container_name: my_project_web
        command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/app
        ports:
            - '8000:8000'
        depends_on:
            - db
        environment:
            # Data base connections parameters
            DB_NAME: mydb
            DB_USER: myuser
            DB_PASSWORD: mypass
            DB_HOST: db
            DB_PORT: 5432
            STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
            STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
            STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

    proxy:
        build:
            context: ./proxy
            dockerfile: proxy.docker
        container_name: cors_proxy
        ports:
            - '1331:1331'
        depends_on:
            - web

    frontend:
        build:
            context: ./frontend
            dockerfile: frontend.docker
        container_name: frontend_app
        ports:
            - '3000:3000'
        depends_on:
            - proxy
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        restart: unless-stopped

volumes:
    postgres_data:
