# Generated by Django 5.1.6 on 2025-02-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auction_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='active',
        ),
        migrations.AddField(
            model_name='auction',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
